// Central registry of every showcased component. The sidebar and the dynamic
// `components/[slug]` route both read from this list. `slug` matches the
// component directory under `$lib/components/<slug>` AND the demo file at
// `routes/demos/<slug>.svelte`.

export type ComponentMeta = {
	slug: string;
	title: string;
	description: string;
};

export const components: ComponentMeta[] = [
	{ slug: 'accordion', title: 'Accordion', description: 'A vertically stacked set of interactive headings that each reveal a section of content.' },
	{ slug: 'alert', title: 'Alert', description: 'Displays a callout for user attention.' },
	{ slug: 'alert-dialog', title: 'Alert Dialog', description: 'A modal dialog that interrupts the user with important content and expects a response.' },
	{ slug: 'aspect-ratio', title: 'Aspect Ratio', description: 'Displays content within a desired ratio.' },
	{ slug: 'avatar', title: 'Avatar', description: 'An image element with a fallback for representing the user.' },
	{ slug: 'badge', title: 'Badge', description: 'Displays a badge or a component that looks like a badge.' },
	{ slug: 'breadcrumb', title: 'Breadcrumb', description: 'Displays the path to the current resource using a hierarchy of links.' },
	{ slug: 'button', title: 'Button', description: 'Displays a button or a component that looks like a button.' },
	{ slug: 'button-group', title: 'Button Group', description: 'Groups a set of related buttons together with shared borders.' },
	{ slug: 'calendar', title: 'Calendar', description: 'A calendar component for selecting and displaying dates.' },
	{ slug: 'card', title: 'Card', description: 'A container with a header, content, and footer.' },
	{ slug: 'carousel', title: 'Carousel', description: 'A carousel for cycling through a set of items.' },
	{ slug: 'chart', title: 'Chart', description: 'Composable charts for visualizing data.' },
	{ slug: 'checkbox', title: 'Checkbox', description: 'A control that toggles between checked and unchecked.' },
	{ slug: 'collapsible', title: 'Collapsible', description: 'An interactive component which expands and collapses a panel.' },
	{ slug: 'combobox', title: 'Combobox', description: 'An autocomplete input with a filterable list of suggestions.' },
	{ slug: 'command', title: 'Command', description: 'A fast, composable command menu.' },
	{ slug: 'context-menu', title: 'Context Menu', description: 'A menu of actions triggered by right-click.' },
	{ slug: 'data-table', title: 'Data Table', description: 'A feature-rich table for displaying tabular data.' },
	{ slug: 'date-field', title: 'Date Field', description: 'Lets users enter and edit a date as individual segments.' },
	{ slug: 'date-picker', title: 'Date Picker', description: 'Combines a calendar with a date field for picking a date.' },
	{ slug: 'date-range-field', title: 'Date Range Field', description: 'Lets users enter and edit a range of dates as segments.' },
	{ slug: 'date-range-picker', title: 'Date Range Picker', description: 'A calendar and field for selecting a range of dates.' },
	{ slug: 'dialog', title: 'Dialog', description: 'A window overlaid on the page, rendering the content underneath inert.' },
	{ slug: 'drawer', title: 'Drawer', description: 'A panel that slides out from the edge of the screen.' },
	{ slug: 'dropdown-menu', title: 'Dropdown Menu', description: 'A menu of actions or options triggered by a button.' },
	{ slug: 'empty', title: 'Empty', description: 'An empty-state placeholder for when there is no content.' },
	{ slug: 'field', title: 'Field', description: 'A form field wrapper with label, description, and validation.' },
	{ slug: 'heading', title: 'Heading', description: 'Semantic, consistently styled headings.' },
	{ slug: 'hover-card', title: 'Hover Card', description: 'Previews content available behind a link on hover.' },
	{ slug: 'input', title: 'Input', description: 'A form input field.' },
	{ slug: 'input-group', title: 'Input Group', description: 'Groups an input with addons like buttons, icons, or text.' },
	{ slug: 'input-otp', title: 'Input OTP', description: 'An accessible one-time-password input.' },
	{ slug: 'item', title: 'Item', description: 'A flexible list item with media, content, and actions.' },
	{ slug: 'kbd', title: 'Kbd', description: 'Displays keyboard keys or shortcuts.' },
	{ slug: 'label', title: 'Label', description: 'An accessible label associated with a control.' },
	{ slug: 'link-preview', title: 'Link Preview', description: 'Previews the content behind a link on hover.' },
	{ slug: 'menubar', title: 'Menubar', description: 'A persistent menu bar common in desktop applications.' },
	{ slug: 'meter', title: 'Meter', description: 'Displays a measurement within a known range.' },
	{ slug: 'navigation-menu', title: 'Navigation Menu', description: 'A collection of links for navigating a site.' },
	{ slug: 'pagination', title: 'Pagination', description: 'Page navigation with next and previous links.' },
	{ slug: 'pin-input', title: 'Pin Input', description: 'An input for entering a sequence of single characters.' },
	{ slug: 'popover', title: 'Popover', description: 'Displays rich content in a portal, triggered by a button.' },
	{ slug: 'progress', title: 'Progress', description: 'Shows the completion progress of a task.' },
	{ slug: 'radio-group', title: 'Radio Group', description: 'A set of checkable buttons where only one can be checked at a time.' },
	{ slug: 'range-calendar', title: 'Range Calendar', description: 'A calendar for selecting a range of dates.' },
	{ slug: 'rating-group', title: 'Rating Group', description: 'A group of icons for capturing or displaying a rating.' },
	{ slug: 'resizable', title: 'Resizable', description: 'Accessible resizable panel groups and layouts.' },
	{ slug: 'scroll-area', title: 'Scroll Area', description: 'Augments native scroll with custom, cross-browser styling.' },
	{ slug: 'select', title: 'Select', description: 'A styled native HTML select element.' },
	{ slug: 'separator', title: 'Separator', description: 'Visually or semantically separates content.' },
	{ slug: 'share-card', title: 'Share Card', description: 'A card for sharing content with a preview and actions.' },
	{ slug: 'sheet', title: 'Sheet', description: 'Extends the dialog to display complementary content from a screen edge.' },
	{ slug: 'sidebar', title: 'Sidebar', description: 'A composable, themeable sidebar for app navigation.' },
	{ slug: 'skeleton', title: 'Skeleton', description: 'A placeholder shown while content is loading.' },
	{ slug: 'slider', title: 'Slider', description: 'Select a value from a given range by dragging a thumb.' },
	{ slug: 'sonner', title: 'Sonner', description: 'An opinionated toast notification component.' },
	{ slug: 'spinner', title: 'Spinner', description: 'An animated loading indicator.' },
	{ slug: 'switch', title: 'Switch', description: 'A control that toggles between an on and off state.' },
	{ slug: 'table', title: 'Table', description: 'A responsive, styled table.' },
	{ slug: 'tabs', title: 'Tabs', description: 'Layered sections of content displayed one panel at a time.' },
	{ slug: 'textarea', title: 'Textarea', description: 'A multi-line form text field.' },
	{ slug: 'theme-toggle', title: 'Theme Toggle', description: 'A button that toggles between light and dark mode.' },
	{ slug: 'time-field', title: 'Time Field', description: 'Lets users enter and edit a time as individual segments.' },
	{ slug: 'time-range-field', title: 'Time Range Field', description: 'Lets users enter and edit a range of times as segments.' },
	{ slug: 'toggle', title: 'Toggle', description: 'A two-state button that can be on or off.' },
	{ slug: 'toggle-group', title: 'Toggle Group', description: 'A set of two-state buttons that can be toggled on or off.' },
	{ slug: 'toolbar', title: 'Toolbar', description: 'A container for grouping a set of controls.' },
	{ slug: 'tooltip', title: 'Tooltip', description: 'A popup that shows information related to an element on hover or focus.' },
];

export const componentBySlug = new Map(components.map((c) => [c.slug, c]));
