// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const blocks = [
	"alert-modal",
	"Appearance",
	"BoundaryFailed",
	"calendar",
	"copy-button",
	"date-picker",
	"ErrorPage",
	"Footer",
	"Header",
	"MobileNav",
	"mockups",
	"PhoneInput",
	"Section",
	"stripe-payment-field",
	"tab-nav",
	"time-picker",
	"user-avatar",
	"verification-code-field",
] as const;
