// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const blocks = [
	"alert-modal",
	"Appearance",
	"calendar",
	"copy-button",
	"date-picker",
	"PhoneInput",
	"tab-nav",
	"time-picker",
	"user-avatar",
] as const;
