// This file is autogenerated by scripts/build-registry.mjs
// Do not edit this file directly. Run `bun run scripts/build-registry.mjs`.

export const componentDemos = {
	"accordion": [
		{
			"path": "/src/lib/registry/examples/accordion/01-accordion.svelte",
			"key": "01-accordion"
		}
	],
	"alert": [
		{
			"path": "/src/lib/registry/examples/alert/01-alert.svelte",
			"key": "01-alert"
		},
		{
			"path": "/src/lib/registry/examples/alert/02-destructive.svelte",
			"key": "02-destructive"
		}
	],
	"alert-dialog": [
		{
			"path": "/src/lib/registry/examples/alert-dialog/01-alert-dialog.svelte",
			"key": "01-alert-dialog"
		}
	],
	"avatar": [
		{
			"path": "/src/lib/registry/examples/avatar/01-avatar.svelte",
			"key": "01-avatar"
		},
		{
			"path": "/src/lib/registry/examples/avatar/02-group.svelte",
			"key": "02-group"
		}
	],
	"badge": [
		{
			"path": "/src/lib/registry/examples/badge/01-variants.svelte",
			"key": "01-variants"
		}
	],
	"breadcrumb": [
		{
			"path": "/src/lib/registry/examples/breadcrumb/01-breadcrumb.svelte",
			"key": "01-breadcrumb"
		}
	],
	"button": [
		{
			"path": "/src/lib/registry/examples/button/01-variants.svelte",
			"key": "01-variants"
		},
		{
			"path": "/src/lib/registry/examples/button/02-sizes.svelte",
			"key": "02-sizes"
		},
		{
			"path": "/src/lib/registry/examples/button/03-with-icon.svelte",
			"key": "03-with-icon"
		}
	],
	"calendar": [
		{
			"path": "/src/lib/registry/examples/calendar/01-calendar.svelte",
			"key": "01-calendar"
		}
	],
	"card": [
		{
			"path": "/src/lib/registry/examples/card/01-card.svelte",
			"key": "01-card"
		}
	],
	"carousel": [
		{
			"path": "/src/lib/registry/examples/carousel/01-carousel.svelte",
			"key": "01-carousel"
		}
	],
	"chart": [
		{
			"path": "/src/lib/registry/examples/chart/01-chart.svelte",
			"key": "01-chart"
		}
	],
	"checkbox": [
		{
			"path": "/src/lib/registry/examples/checkbox/01-checkbox.svelte",
			"key": "01-checkbox"
		},
		{
			"path": "/src/lib/registry/examples/checkbox/02-group.svelte",
			"key": "02-group"
		},
		{
			"path": "/src/lib/registry/examples/checkbox/03-disabled.svelte",
			"key": "03-disabled"
		}
	],
	"collapsible": [
		{
			"path": "/src/lib/registry/examples/collapsible/01-collapsible.svelte",
			"key": "01-collapsible"
		}
	],
	"combobox": [
		{
			"path": "/src/lib/registry/examples/combobox/01-combobox.svelte",
			"key": "01-combobox"
		}
	],
	"command": [
		{
			"path": "/src/lib/registry/examples/command/01-command.svelte",
			"key": "01-command"
		}
	],
	"context-menu": [
		{
			"path": "/src/lib/registry/examples/context-menu/01-context-menu.svelte",
			"key": "01-context-menu"
		}
	],
	"data-table": [
		{
			"path": "/src/lib/registry/examples/data-table/01-data-table.svelte",
			"key": "01-data-table"
		}
	],
	"date-field": [
		{
			"path": "/src/lib/registry/examples/date-field/01-date-field.svelte",
			"key": "01-date-field"
		}
	],
	"date-picker": [
		{
			"path": "/src/lib/registry/examples/date-picker/01-date-picker.svelte",
			"key": "01-date-picker"
		},
		{
			"path": "/src/lib/registry/examples/date-picker/02-presets.svelte",
			"key": "02-presets"
		},
		{
			"path": "/src/lib/registry/examples/date-picker/03-range.svelte",
			"key": "03-range"
		}
	],
	"date-range-field": [
		{
			"path": "/src/lib/registry/examples/date-range-field/01-date-range-field.svelte",
			"key": "01-date-range-field"
		}
	],
	"dialog": [
		{
			"path": "/src/lib/registry/examples/dialog/01-dialog.svelte",
			"key": "01-dialog"
		}
	],
	"drawer": [
		{
			"path": "/src/lib/registry/examples/drawer/01-drawer.svelte",
			"key": "01-drawer"
		}
	],
	"dropdown-menu": [
		{
			"path": "/src/lib/registry/examples/dropdown-menu/01-dropdown-menu.svelte",
			"key": "01-dropdown-menu"
		}
	],
	"empty": [
		{
			"path": "/src/lib/registry/examples/empty/01-empty.svelte",
			"key": "01-empty"
		}
	],
	"field": [
		{
			"path": "/src/lib/registry/examples/field/01-field.svelte",
			"key": "01-field"
		}
	],
	"heading": [
		{
			"path": "/src/lib/registry/examples/heading/01-heading.svelte",
			"key": "01-heading"
		}
	],
	"input": [
		{
			"path": "/src/lib/registry/examples/input/01-input.svelte",
			"key": "01-input"
		}
	],
	"item": [
		{
			"path": "/src/lib/registry/examples/item/01-item.svelte",
			"key": "01-item"
		}
	],
	"kbd": [
		{
			"path": "/src/lib/registry/examples/kbd/01-kbd.svelte",
			"key": "01-kbd"
		}
	],
	"label": [
		{
			"path": "/src/lib/registry/examples/label/01-label.svelte",
			"key": "01-label"
		}
	],
	"link-preview": [
		{
			"path": "/src/lib/registry/examples/link-preview/01-link-preview.svelte",
			"key": "01-link-preview"
		}
	],
	"menubar": [
		{
			"path": "/src/lib/registry/examples/menubar/01-menubar.svelte",
			"key": "01-menubar"
		}
	],
	"meter": [
		{
			"path": "/src/lib/registry/examples/meter/01-meter.svelte",
			"key": "01-meter"
		}
	],
	"native-select": [
		{
			"path": "/src/lib/registry/examples/native-select/01-native-select.svelte",
			"key": "01-native-select"
		}
	],
	"navigation-menu": [
		{
			"path": "/src/lib/registry/examples/navigation-menu/01-navigation-menu.svelte",
			"key": "01-navigation-menu"
		}
	],
	"pagination": [
		{
			"path": "/src/lib/registry/examples/pagination/01-pagination.svelte",
			"key": "01-pagination"
		}
	],
	"pin-input": [
		{
			"path": "/src/lib/registry/examples/pin-input/01-pin-input.svelte",
			"key": "01-pin-input"
		}
	],
	"popover": [
		{
			"path": "/src/lib/registry/examples/popover/01-popover.svelte",
			"key": "01-popover"
		}
	],
	"progress": [
		{
			"path": "/src/lib/registry/examples/progress/01-progress.svelte",
			"key": "01-progress"
		}
	],
	"radio-group": [
		{
			"path": "/src/lib/registry/examples/radio-group/01-radio-group.svelte",
			"key": "01-radio-group"
		}
	],
	"range-calendar": [
		{
			"path": "/src/lib/registry/examples/range-calendar/01-range-calendar.svelte",
			"key": "01-range-calendar"
		}
	],
	"resizable": [
		{
			"path": "/src/lib/registry/examples/resizable/01-resizable.svelte",
			"key": "01-resizable"
		}
	],
	"scroll-area": [
		{
			"path": "/src/lib/registry/examples/scroll-area/01-scroll-area.svelte",
			"key": "01-scroll-area"
		}
	],
	"select": [
		{
			"path": "/src/lib/registry/examples/select/01-select.svelte",
			"key": "01-select"
		}
	],
	"separator": [
		{
			"path": "/src/lib/registry/examples/separator/01-separator.svelte",
			"key": "01-separator"
		}
	],
	"sheet": [
		{
			"path": "/src/lib/registry/examples/sheet/01-sheet.svelte",
			"key": "01-sheet"
		},
		{
			"path": "/src/lib/registry/examples/sheet/02-side.svelte",
			"key": "02-side"
		}
	],
	"sidebar": [
		{
			"path": "/src/lib/registry/examples/sidebar/01-sidebar.svelte",
			"key": "01-sidebar"
		}
	],
	"skeleton": [
		{
			"path": "/src/lib/registry/examples/skeleton/01-skeleton.svelte",
			"key": "01-skeleton"
		}
	],
	"slider": [
		{
			"path": "/src/lib/registry/examples/slider/01-slider.svelte",
			"key": "01-slider"
		},
		{
			"path": "/src/lib/registry/examples/slider/02-range.svelte",
			"key": "02-range"
		}
	],
	"sonner": [
		{
			"path": "/src/lib/registry/examples/sonner/01-sonner.svelte",
			"key": "01-sonner"
		}
	],
	"spinner": [
		{
			"path": "/src/lib/registry/examples/spinner/01-spinner.svelte",
			"key": "01-spinner"
		}
	],
	"switch": [
		{
			"path": "/src/lib/registry/examples/switch/01-switch.svelte",
			"key": "01-switch"
		}
	],
	"switch-native": [
		{
			"path": "/src/lib/registry/examples/switch-native/01-switch-native.svelte",
			"key": "01-switch-native"
		}
	],
	"table": [
		{
			"path": "/src/lib/registry/examples/table/01-table.svelte",
			"key": "01-table"
		}
	],
	"tabs": [
		{
			"path": "/src/lib/registry/examples/tabs/01-tabs.svelte",
			"key": "01-tabs"
		}
	],
	"textarea": [
		{
			"path": "/src/lib/registry/examples/textarea/01-textarea.svelte",
			"key": "01-textarea"
		}
	],
	"theme-toggle": [
		{
			"path": "/src/lib/registry/examples/theme-toggle/01-theme-toggle.svelte",
			"key": "01-theme-toggle"
		}
	],
	"time-field": [
		{
			"path": "/src/lib/registry/examples/time-field/01-time-field.svelte",
			"key": "01-time-field"
		}
	],
	"time-range-field": [
		{
			"path": "/src/lib/registry/examples/time-range-field/01-time-range-field.svelte",
			"key": "01-time-range-field"
		}
	],
	"toggle": [
		{
			"path": "/src/lib/registry/examples/toggle/01-toggle.svelte",
			"key": "01-toggle"
		},
		{
			"path": "/src/lib/registry/examples/toggle/02-outline.svelte",
			"key": "02-outline"
		},
		{
			"path": "/src/lib/registry/examples/toggle/03-disabled.svelte",
			"key": "03-disabled"
		}
	],
	"toggle-group": [
		{
			"path": "/src/lib/registry/examples/toggle-group/01-toggle-group.svelte",
			"key": "01-toggle-group"
		},
		{
			"path": "/src/lib/registry/examples/toggle-group/02-multiple.svelte",
			"key": "02-multiple"
		}
	],
	"toolbar": [
		{
			"path": "/src/lib/registry/examples/toolbar/01-toolbar.svelte",
			"key": "01-toolbar"
		}
	],
	"tooltip": [
		{
			"path": "/src/lib/registry/examples/tooltip/01-tooltip.svelte",
			"key": "01-tooltip"
		}
	]
};

export const slugsWithDemos = new Set(Object.keys(componentDemos));
