// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const components = [
	{"slug":"accordion","name":"Accordion","description":"A vertically stacked set of interactive headings that each reveal a section of content."},
	{"slug":"alert","name":"Alert","description":"Displays a callout for user attention."},
	{"slug":"alert-dialog","name":"Alert Dialog","description":"A modal dialog that interrupts the user with important content and expects a response."},
	{"slug":"avatar","name":"Avatar","description":"An image element with a fallback for representing the user."},
	{"slug":"badge","name":"Badge","description":"Displays a badge or a component that looks like a badge."},
	{"slug":"breadcrumb","name":"Breadcrumb","description":"Displays the path to the current resource using a hierarchy of links."},
	{"slug":"button","name":"Button","description":"Displays a button or a component that looks like a button."},
	{"slug":"calendar","name":"Calendar","description":"A calendar component that allows users to select a date."},
	{"slug":"card","name":"Card","description":"Displays a card with header, content, and footer."},
	{"slug":"carousel","name":"Carousel","description":"A carousel with motion and swipe built using Embla."},
	{"slug":"chart","name":"Chart","description":"Visualize data with composable charts built on LayerChart."},
	{"slug":"checkbox","name":"Checkbox","description":"A control that allows the user to toggle between checked and not checked."},
	{"slug":"collapsible","name":"Collapsible","description":"An interactive component which expands and collapses a panel."},
	{"slug":"combobox","name":"Combobox","description":"Autocomplete input with a filterable list of suggestions."},
	{"slug":"command","name":"Command","description":"A fast, composable command menu."},
	{"slug":"context-menu","name":"Context Menu","description":"Displays a menu of actions triggered by a right click."},
	{"slug":"data-table","name":"Data Table","description":"Powerful tables and datagrids built using TanStack Table."},
	{"slug":"date-field","name":"Date Field","description":"A segmented field that lets users enter and edit a date."},
	{"slug":"date-picker","name":"Date Picker","description":"A date field paired with a calendar popover."},
	{"slug":"date-range-field","name":"Date Range Field","description":"A segmented field that lets users enter and edit a range of dates."},
	{"slug":"dialog","name":"Dialog","description":"A window overlaid on the primary content, rendering the content underneath inert."},
	{"slug":"drawer","name":"Drawer","description":"A panel that slides in from the edge of the screen."},
	{"slug":"dropdown-menu","name":"Dropdown Menu","description":"Displays a menu of actions triggered by a button."},
	{"slug":"empty","name":"Empty","description":"Display an empty state with a heading, description, and actions."},
	{"slug":"field","name":"Field","description":"Compose accessible form fields from labels, controls, and help text."},
	{"slug":"heading","name":"Heading","description":"A heading component for page and section titles."},
	{"slug":"input","name":"Input","description":"Displays a form input field or a component that looks like an input field."},
	{"slug":"item","name":"Item","description":"A flexible, composable row for displaying content with media and actions."},
	{"slug":"kbd","name":"Kbd","description":"Display textual user input from a keyboard."},
	{"slug":"label","name":"Label","description":"Renders an accessible label associated with a control."},
	{"slug":"link-preview","name":"Link Preview","description":"Previews content behind a link when hovering over it."},
	{"slug":"menubar","name":"Menubar","description":"A persistent menu bar providing quick access to a consistent set of commands."},
	{"slug":"meter","name":"Meter","description":"Displays a value within a known range."},
	{"slug":"native-select","name":"Native Select","description":"A native select element for choosing from a list of options."},
	{"slug":"navigation-menu","name":"Navigation Menu","description":"A collection of links for navigating a site."},
	{"slug":"pagination","name":"Pagination","description":"Page navigation with next and previous links."},
	{"slug":"pin-input","name":"Pin Input","description":"An accessible one-time-password / pin entry input."},
	{"slug":"popover","name":"Popover","description":"Displays rich content in a portal, triggered by a button."},
	{"slug":"progress","name":"Progress","description":"Displays an indicator showing the completion progress of a task."},
	{"slug":"radio-group","name":"Radio Group","description":"A set of checkable buttons where only one can be checked at a time."},
	{"slug":"range-calendar","name":"Range Calendar","description":"A calendar component that allows users to select a range of dates."},
	{"slug":"resizable","name":"Resizable","description":"Accessible resizable panel groups and layouts."},
	{"slug":"scroll-area","name":"Scroll Area","description":"Augments native scroll with custom, cross-browser styling."},
	{"slug":"select","name":"Select","description":"Displays a list of options for the user to pick from, triggered by a button."},
	{"slug":"separator","name":"Separator","description":"Visually or semantically separates content."},
	{"slug":"sheet","name":"Sheet","description":"A dialog that slides in to complement the main content of the screen."},
	{"slug":"sidebar","name":"Sidebar","description":"A composable, themeable and customizable sidebar component."},
	{"slug":"skeleton","name":"Skeleton","description":"Show a placeholder while content is loading."},
	{"slug":"slider","name":"Slider","description":"An input where the user selects a value from within a given range."},
	{"slug":"sonner","name":"Sonner","description":"An opinionated toast component."},
	{"slug":"spinner","name":"Spinner","description":"An indicator that shows a loading state."},
	{"slug":"switch","name":"Switch","description":"A control that allows the user to toggle between checked and not checked."},
	{"slug":"switch-native","name":"Switch (Native)","description":"A native checkbox-based switch control."},
	{"slug":"table","name":"Table","description":"A responsive table component."},
	{"slug":"tabs","name":"Tabs","description":"Layered sections of content displayed one panel at a time."},
	{"slug":"textarea","name":"Textarea","description":"Displays a form textarea or a component that looks like a textarea."},
	{"slug":"theme-toggle","name":"Theme Toggle","description":"A button that toggles between light and dark mode."},
	{"slug":"time-field","name":"Time Field","description":"A segmented field that lets users enter and edit a time."},
	{"slug":"time-range-field","name":"Time Range Field","description":"A segmented field that lets users enter and edit a range of times."},
	{"slug":"toggle","name":"Toggle","description":"A two-state button that can be either on or off."},
	{"slug":"toggle-group","name":"Toggle Group","description":"A set of two-state buttons that can be toggled on or off."},
	{"slug":"toolbar","name":"Toolbar","description":"A container for grouping a set of controls such as buttons and toggles."},
	{"slug":"tooltip","name":"Tooltip","description":"A popup that displays information related to an element on hover or focus."},
] as const;

export const componentDemos = {
	"accordion": [
		{ key: "01-accordion", name: "accordion-01-accordion", path: "/src/lib/registry/examples/accordion/01-accordion.svelte", sourcePath: "../lib/registry/examples/accordion/01-accordion.svelte" },
	],
	"alert": [
		{ key: "01-alert", name: "alert-01-alert", path: "/src/lib/registry/examples/alert/01-alert.svelte", sourcePath: "../lib/registry/examples/alert/01-alert.svelte" },
	],
	"alert-dialog": [
		{ key: "01-alert-dialog", name: "alert-dialog-01-alert-dialog", path: "/src/lib/registry/examples/alert-dialog/01-alert-dialog.svelte", sourcePath: "../lib/registry/examples/alert-dialog/01-alert-dialog.svelte" },
	],
	"avatar": [
		{ key: "01-avatar", name: "avatar-01-avatar", path: "/src/lib/registry/examples/avatar/01-avatar.svelte", sourcePath: "../lib/registry/examples/avatar/01-avatar.svelte" },
		{ key: "02-group", name: "avatar-02-group", path: "/src/lib/registry/examples/avatar/02-group.svelte", sourcePath: "../lib/registry/examples/avatar/02-group.svelte" },
	],
	"badge": [
		{ key: "01-variants", name: "badge-01-variants", path: "/src/lib/registry/examples/badge/01-variants.svelte", sourcePath: "../lib/registry/examples/badge/01-variants.svelte" },
	],
	"breadcrumb": [
		{ key: "01-breadcrumb", name: "breadcrumb-01-breadcrumb", path: "/src/lib/registry/examples/breadcrumb/01-breadcrumb.svelte", sourcePath: "../lib/registry/examples/breadcrumb/01-breadcrumb.svelte" },
	],
	"button": [
		{ key: "01-variants", name: "button-01-variants", path: "/src/lib/registry/examples/button/01-variants.svelte", sourcePath: "../lib/registry/examples/button/01-variants.svelte" },
		{ key: "02-sizes", name: "button-02-sizes", path: "/src/lib/registry/examples/button/02-sizes.svelte", sourcePath: "../lib/registry/examples/button/02-sizes.svelte" },
		{ key: "03-with-icon", name: "button-03-with-icon", path: "/src/lib/registry/examples/button/03-with-icon.svelte", sourcePath: "../lib/registry/examples/button/03-with-icon.svelte" },
	],
	"calendar": [
		{ key: "01-calendar", name: "calendar-01-calendar", path: "/src/lib/registry/examples/calendar/01-calendar.svelte", sourcePath: "../lib/registry/examples/calendar/01-calendar.svelte" },
	],
	"card": [
		{ key: "01-card", name: "card-01-card", path: "/src/lib/registry/examples/card/01-card.svelte", sourcePath: "../lib/registry/examples/card/01-card.svelte" },
	],
	"carousel": [
		{ key: "01-carousel", name: "carousel-01-carousel", path: "/src/lib/registry/examples/carousel/01-carousel.svelte", sourcePath: "../lib/registry/examples/carousel/01-carousel.svelte" },
	],
	"chart": [
		{ key: "01-chart", name: "chart-01-chart", path: "/src/lib/registry/examples/chart/01-chart.svelte", sourcePath: "../lib/registry/examples/chart/01-chart.svelte" },
	],
	"checkbox": [
		{ key: "01-checkbox", name: "checkbox-01-checkbox", path: "/src/lib/registry/examples/checkbox/01-checkbox.svelte", sourcePath: "../lib/registry/examples/checkbox/01-checkbox.svelte" },
		{ key: "02-group", name: "checkbox-02-group", path: "/src/lib/registry/examples/checkbox/02-group.svelte", sourcePath: "../lib/registry/examples/checkbox/02-group.svelte" },
		{ key: "03-disabled", name: "checkbox-03-disabled", path: "/src/lib/registry/examples/checkbox/03-disabled.svelte", sourcePath: "../lib/registry/examples/checkbox/03-disabled.svelte" },
	],
	"collapsible": [
		{ key: "01-collapsible", name: "collapsible-01-collapsible", path: "/src/lib/registry/examples/collapsible/01-collapsible.svelte", sourcePath: "../lib/registry/examples/collapsible/01-collapsible.svelte" },
	],
	"combobox": [
		{ key: "01-combobox", name: "combobox-01-combobox", path: "/src/lib/registry/examples/combobox/01-combobox.svelte", sourcePath: "../lib/registry/examples/combobox/01-combobox.svelte" },
	],
	"command": [
		{ key: "01-command", name: "command-01-command", path: "/src/lib/registry/examples/command/01-command.svelte", sourcePath: "../lib/registry/examples/command/01-command.svelte" },
	],
	"context-menu": [
		{ key: "01-context-menu", name: "context-menu-01-context-menu", path: "/src/lib/registry/examples/context-menu/01-context-menu.svelte", sourcePath: "../lib/registry/examples/context-menu/01-context-menu.svelte" },
	],
	"data-table": [
		{ key: "01-data-table", name: "data-table-01-data-table", path: "/src/lib/registry/examples/data-table/01-data-table.svelte", sourcePath: "../lib/registry/examples/data-table/01-data-table.svelte" },
	],
	"date-field": [
		{ key: "01-date-field", name: "date-field-01-date-field", path: "/src/lib/registry/examples/date-field/01-date-field.svelte", sourcePath: "../lib/registry/examples/date-field/01-date-field.svelte" },
	],
	"date-picker": [
		{ key: "01-date-picker", name: "date-picker-01-date-picker", path: "/src/lib/registry/examples/date-picker/01-date-picker.svelte", sourcePath: "../lib/registry/examples/date-picker/01-date-picker.svelte" },
		{ key: "02-presets", name: "date-picker-02-presets", path: "/src/lib/registry/examples/date-picker/02-presets.svelte", sourcePath: "../lib/registry/examples/date-picker/02-presets.svelte" },
		{ key: "03-range", name: "date-picker-03-range", path: "/src/lib/registry/examples/date-picker/03-range.svelte", sourcePath: "../lib/registry/examples/date-picker/03-range.svelte" },
	],
	"date-range-field": [
		{ key: "01-date-range-field", name: "date-range-field-01-date-range-field", path: "/src/lib/registry/examples/date-range-field/01-date-range-field.svelte", sourcePath: "../lib/registry/examples/date-range-field/01-date-range-field.svelte" },
	],
	"dialog": [
		{ key: "01-dialog", name: "dialog-01-dialog", path: "/src/lib/registry/examples/dialog/01-dialog.svelte", sourcePath: "../lib/registry/examples/dialog/01-dialog.svelte" },
	],
	"drawer": [
		{ key: "01-drawer", name: "drawer-01-drawer", path: "/src/lib/registry/examples/drawer/01-drawer.svelte", sourcePath: "../lib/registry/examples/drawer/01-drawer.svelte" },
	],
	"dropdown-menu": [
		{ key: "01-dropdown-menu", name: "dropdown-menu-01-dropdown-menu", path: "/src/lib/registry/examples/dropdown-menu/01-dropdown-menu.svelte", sourcePath: "../lib/registry/examples/dropdown-menu/01-dropdown-menu.svelte" },
	],
	"empty": [
		{ key: "01-empty", name: "empty-01-empty", path: "/src/lib/registry/examples/empty/01-empty.svelte", sourcePath: "../lib/registry/examples/empty/01-empty.svelte" },
	],
	"field": [
		{ key: "01-field", name: "field-01-field", path: "/src/lib/registry/examples/field/01-field.svelte", sourcePath: "../lib/registry/examples/field/01-field.svelte" },
	],
	"heading": [
		{ key: "01-heading", name: "heading-01-heading", path: "/src/lib/registry/examples/heading/01-heading.svelte", sourcePath: "../lib/registry/examples/heading/01-heading.svelte" },
	],
	"input": [
		{ key: "01-input", name: "input-01-input", path: "/src/lib/registry/examples/input/01-input.svelte", sourcePath: "../lib/registry/examples/input/01-input.svelte" },
	],
	"item": [
		{ key: "01-item", name: "item-01-item", path: "/src/lib/registry/examples/item/01-item.svelte", sourcePath: "../lib/registry/examples/item/01-item.svelte" },
	],
	"kbd": [
		{ key: "01-kbd", name: "kbd-01-kbd", path: "/src/lib/registry/examples/kbd/01-kbd.svelte", sourcePath: "../lib/registry/examples/kbd/01-kbd.svelte" },
	],
	"label": [
		{ key: "01-label", name: "label-01-label", path: "/src/lib/registry/examples/label/01-label.svelte", sourcePath: "../lib/registry/examples/label/01-label.svelte" },
	],
	"link-preview": [
		{ key: "01-link-preview", name: "link-preview-01-link-preview", path: "/src/lib/registry/examples/link-preview/01-link-preview.svelte", sourcePath: "../lib/registry/examples/link-preview/01-link-preview.svelte" },
	],
	"menubar": [
		{ key: "01-menubar", name: "menubar-01-menubar", path: "/src/lib/registry/examples/menubar/01-menubar.svelte", sourcePath: "../lib/registry/examples/menubar/01-menubar.svelte" },
	],
	"meter": [
		{ key: "01-meter", name: "meter-01-meter", path: "/src/lib/registry/examples/meter/01-meter.svelte", sourcePath: "../lib/registry/examples/meter/01-meter.svelte" },
	],
	"native-select": [
		{ key: "01-native-select", name: "native-select-01-native-select", path: "/src/lib/registry/examples/native-select/01-native-select.svelte", sourcePath: "../lib/registry/examples/native-select/01-native-select.svelte" },
	],
	"navigation-menu": [
		{ key: "01-navigation-menu", name: "navigation-menu-01-navigation-menu", path: "/src/lib/registry/examples/navigation-menu/01-navigation-menu.svelte", sourcePath: "../lib/registry/examples/navigation-menu/01-navigation-menu.svelte" },
	],
	"pagination": [
		{ key: "01-pagination", name: "pagination-01-pagination", path: "/src/lib/registry/examples/pagination/01-pagination.svelte", sourcePath: "../lib/registry/examples/pagination/01-pagination.svelte" },
	],
	"pin-input": [
		{ key: "01-pin-input", name: "pin-input-01-pin-input", path: "/src/lib/registry/examples/pin-input/01-pin-input.svelte", sourcePath: "../lib/registry/examples/pin-input/01-pin-input.svelte" },
	],
	"popover": [
		{ key: "01-popover", name: "popover-01-popover", path: "/src/lib/registry/examples/popover/01-popover.svelte", sourcePath: "../lib/registry/examples/popover/01-popover.svelte" },
	],
	"progress": [
		{ key: "01-progress", name: "progress-01-progress", path: "/src/lib/registry/examples/progress/01-progress.svelte", sourcePath: "../lib/registry/examples/progress/01-progress.svelte" },
	],
	"radio-group": [
		{ key: "01-radio-group", name: "radio-group-01-radio-group", path: "/src/lib/registry/examples/radio-group/01-radio-group.svelte", sourcePath: "../lib/registry/examples/radio-group/01-radio-group.svelte" },
	],
	"range-calendar": [
		{ key: "01-range-calendar", name: "range-calendar-01-range-calendar", path: "/src/lib/registry/examples/range-calendar/01-range-calendar.svelte", sourcePath: "../lib/registry/examples/range-calendar/01-range-calendar.svelte" },
	],
	"resizable": [
		{ key: "01-resizable", name: "resizable-01-resizable", path: "/src/lib/registry/examples/resizable/01-resizable.svelte", sourcePath: "../lib/registry/examples/resizable/01-resizable.svelte" },
	],
	"scroll-area": [
		{ key: "01-scroll-area", name: "scroll-area-01-scroll-area", path: "/src/lib/registry/examples/scroll-area/01-scroll-area.svelte", sourcePath: "../lib/registry/examples/scroll-area/01-scroll-area.svelte" },
	],
	"select": [
		{ key: "01-select", name: "select-01-select", path: "/src/lib/registry/examples/select/01-select.svelte", sourcePath: "../lib/registry/examples/select/01-select.svelte" },
	],
	"separator": [
		{ key: "01-separator", name: "separator-01-separator", path: "/src/lib/registry/examples/separator/01-separator.svelte", sourcePath: "../lib/registry/examples/separator/01-separator.svelte" },
	],
	"sheet": [
		{ key: "01-sheet", name: "sheet-01-sheet", path: "/src/lib/registry/examples/sheet/01-sheet.svelte", sourcePath: "../lib/registry/examples/sheet/01-sheet.svelte" },
		{ key: "02-side", name: "sheet-02-side", path: "/src/lib/registry/examples/sheet/02-side.svelte", sourcePath: "../lib/registry/examples/sheet/02-side.svelte" },
	],
	"sidebar": [
		{ key: "01-sidebar", name: "sidebar-01-sidebar", path: "/src/lib/registry/examples/sidebar/01-sidebar.svelte", sourcePath: "../lib/registry/examples/sidebar/01-sidebar.svelte" },
	],
	"skeleton": [
		{ key: "01-skeleton", name: "skeleton-01-skeleton", path: "/src/lib/registry/examples/skeleton/01-skeleton.svelte", sourcePath: "../lib/registry/examples/skeleton/01-skeleton.svelte" },
	],
	"slider": [
		{ key: "01-slider", name: "slider-01-slider", path: "/src/lib/registry/examples/slider/01-slider.svelte", sourcePath: "../lib/registry/examples/slider/01-slider.svelte" },
		{ key: "02-range", name: "slider-02-range", path: "/src/lib/registry/examples/slider/02-range.svelte", sourcePath: "../lib/registry/examples/slider/02-range.svelte" },
	],
	"sonner": [
		{ key: "01-sonner", name: "sonner-01-sonner", path: "/src/lib/registry/examples/sonner/01-sonner.svelte", sourcePath: "../lib/registry/examples/sonner/01-sonner.svelte" },
	],
	"spinner": [
		{ key: "01-spinner", name: "spinner-01-spinner", path: "/src/lib/registry/examples/spinner/01-spinner.svelte", sourcePath: "../lib/registry/examples/spinner/01-spinner.svelte" },
	],
	"switch": [
		{ key: "01-switch", name: "switch-01-switch", path: "/src/lib/registry/examples/switch/01-switch.svelte", sourcePath: "../lib/registry/examples/switch/01-switch.svelte" },
	],
	"switch-native": [
		{ key: "01-switch-native", name: "switch-native-01-switch-native", path: "/src/lib/registry/examples/switch-native/01-switch-native.svelte", sourcePath: "../lib/registry/examples/switch-native/01-switch-native.svelte" },
	],
	"table": [
		{ key: "01-table", name: "table-01-table", path: "/src/lib/registry/examples/table/01-table.svelte", sourcePath: "../lib/registry/examples/table/01-table.svelte" },
	],
	"tabs": [
		{ key: "01-tabs", name: "tabs-01-tabs", path: "/src/lib/registry/examples/tabs/01-tabs.svelte", sourcePath: "../lib/registry/examples/tabs/01-tabs.svelte" },
	],
	"textarea": [
		{ key: "01-textarea", name: "textarea-01-textarea", path: "/src/lib/registry/examples/textarea/01-textarea.svelte", sourcePath: "../lib/registry/examples/textarea/01-textarea.svelte" },
	],
	"theme-toggle": [
		{ key: "01-theme-toggle", name: "theme-toggle-01-theme-toggle", path: "/src/lib/registry/examples/theme-toggle/01-theme-toggle.svelte", sourcePath: "../lib/registry/examples/theme-toggle/01-theme-toggle.svelte" },
	],
	"time-field": [
		{ key: "01-time-field", name: "time-field-01-time-field", path: "/src/lib/registry/examples/time-field/01-time-field.svelte", sourcePath: "../lib/registry/examples/time-field/01-time-field.svelte" },
	],
	"time-range-field": [
		{ key: "01-time-range-field", name: "time-range-field-01-time-range-field", path: "/src/lib/registry/examples/time-range-field/01-time-range-field.svelte", sourcePath: "../lib/registry/examples/time-range-field/01-time-range-field.svelte" },
	],
	"toggle": [
		{ key: "01-toggle", name: "toggle-01-toggle", path: "/src/lib/registry/examples/toggle/01-toggle.svelte", sourcePath: "../lib/registry/examples/toggle/01-toggle.svelte" },
		{ key: "02-outline", name: "toggle-02-outline", path: "/src/lib/registry/examples/toggle/02-outline.svelte", sourcePath: "../lib/registry/examples/toggle/02-outline.svelte" },
		{ key: "03-disabled", name: "toggle-03-disabled", path: "/src/lib/registry/examples/toggle/03-disabled.svelte", sourcePath: "../lib/registry/examples/toggle/03-disabled.svelte" },
	],
	"toggle-group": [
		{ key: "01-toggle-group", name: "toggle-group-01-toggle-group", path: "/src/lib/registry/examples/toggle-group/01-toggle-group.svelte", sourcePath: "../lib/registry/examples/toggle-group/01-toggle-group.svelte" },
		{ key: "02-multiple", name: "toggle-group-02-multiple", path: "/src/lib/registry/examples/toggle-group/02-multiple.svelte", sourcePath: "../lib/registry/examples/toggle-group/02-multiple.svelte" },
	],
	"toolbar": [
		{ key: "01-toolbar", name: "toolbar-01-toolbar", path: "/src/lib/registry/examples/toolbar/01-toolbar.svelte", sourcePath: "../lib/registry/examples/toolbar/01-toolbar.svelte" },
	],
	"tooltip": [
		{ key: "01-tooltip", name: "tooltip-01-tooltip", path: "/src/lib/registry/examples/tooltip/01-tooltip.svelte", sourcePath: "../lib/registry/examples/tooltip/01-tooltip.svelte" },
	],
} as const;

export const slugsWithDemos = new Set(
	Object.entries(componentDemos)
		.filter(([, demos]) => demos.length > 0)
		.map(([slug]) => slug)
);
