// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const components = [
	{"slug":"accordion","name":"Accordion","description":"A vertically stacked set of interactive headings that each reveal a section of content."},
	{"slug":"alert","name":"Alert","description":"Displays a callout for user attention."},
	{"slug":"avatar","name":"Avatar","description":"An image element with a fallback for representing the user."},
	{"slug":"badge","name":"Badge","description":"Displays a badge or a component that looks like a badge."},
	{"slug":"breadcrumb","name":"Breadcrumb","description":"Displays the path to the current resource using a hierarchy of links."},
	{"slug":"button","name":"Button","description":"Displays a button or a component that looks like a button."},
	{"slug":"calendar","name":"Calendar","description":"A calendar component that allows users to select a date."},
	{"slug":"card","name":"Card","description":"Displays a card with header, content, and footer."},
	{"slug":"carousel","name":"Carousel","description":"A carousel with motion and swipe built using Embla."},
	{"slug":"carousel-native","name":"Carousel (Native)","description":"A carousel on native scroll snap: the browser owns physics and snapping, selection is read from scrollend."},
	{"slug":"chart","name":"Chart","description":"Visualize data with composable charts built on LayerChart."},
	{"slug":"checkbox","name":"Checkbox","description":"A control that allows the user to toggle between checked and not checked."},
	{"slug":"checkbox-native","name":"Checkbox (Native)","description":"A native form checkbox that submits name/value and supports indeterminate."},
	{"slug":"collapsible","name":"Collapsible","description":"An interactive component which expands and collapses a panel."},
	{"slug":"combobox","name":"Combobox","description":"Autocomplete input with a filterable list of suggestions."},
	{"slug":"command","name":"Command","description":"A fast, composable command menu."},
	{"slug":"context-menu","name":"Context Menu","description":"Displays a menu of actions triggered by a right click."},
	{"slug":"data-table","name":"Data Table","description":"Powerful tables and datagrids built using TanStack Table."},
	{"slug":"date-field","name":"Date Field","description":"A segmented field that lets users enter and edit a date."},
	{"slug":"date-picker","name":"Date Picker","description":"A date field paired with a calendar popover."},
	{"slug":"date-range-field","name":"Date Range Field","description":"A segmented field that lets users enter and edit a range of dates."},
	{"slug":"dialog","name":"Dialog","description":"A window overlaid on the primary content, rendering the content underneath inert."},
	{"slug":"drawer","name":"Drawer","description":"A panel that slides in from the edge of the screen."},
	{"slug":"dropdown-menu","name":"Dropdown Menu","description":"Displays a menu of actions triggered by a button."},
	{"slug":"empty","name":"Empty","description":"Display an empty state with a heading, description, and actions."},
	{"slug":"field","name":"Field","description":"Compose accessible form fields from labels, controls, and help text."},
	{"slug":"heading","name":"Heading","description":"A heading component for page and section titles."},
	{"slug":"input","name":"Input","description":"Displays a form input field or a component that looks like an input field."},
	{"slug":"item","name":"Item","description":"A flexible, composable row for displaying content with media and actions."},
	{"slug":"kbd","name":"Kbd","description":"Display textual user input from a keyboard."},
	{"slug":"label","name":"Label","description":"Renders an accessible label associated with a control."},
	{"slug":"link-preview","name":"Link Preview","description":"Previews content behind a link when hovering over it."},
	{"slug":"menubar","name":"Menubar","description":"A persistent menu bar providing quick access to a consistent set of commands."},
	{"slug":"meter","name":"Meter","description":"Displays a value within a known range."},
	{"slug":"native-dialog","name":"Native Dialog (spike)","description":"A modal dialog built on the native <dialog> element + showModal, as a CSS/HTML spike that drops the JS overlay stack."},
	{"slug":"native-select","name":"Native Select","description":"A native select element for choosing from a list of options."},
	{"slug":"navigation-menu","name":"Navigation Menu","description":"A collection of links for navigating a site."},
	{"slug":"pagination","name":"Pagination","description":"Page navigation with next and previous links."},
	{"slug":"pin-input","name":"Pin Input","description":"An accessible one-time-password / pin entry input."},
	{"slug":"popover","name":"Popover","description":"Displays rich content in a portal, triggered by a button."},
	{"slug":"progress","name":"Progress","description":"Displays an indicator showing the completion progress of a task."},
	{"slug":"radio-group","name":"Radio Group","description":"A set of native radio inputs where only one can be selected at a time."},
	{"slug":"range-calendar","name":"Range Calendar","description":"A calendar component that allows users to select a range of dates."},
	{"slug":"resizable","name":"Resizable","description":"Accessible resizable panel groups and layouts."},
	{"slug":"scroll-area","name":"Scroll Area","description":"Augments native scroll with custom, cross-browser styling."},
	{"slug":"select","name":"Select","description":"Displays a list of options for the user to pick from, triggered by a button."},
	{"slug":"separator","name":"Separator","description":"Visually or semantically separates content."},
	{"slug":"sheet","name":"Sheet","description":"A dialog that slides in to complement the main content of the screen."},
	{"slug":"sidebar","name":"Sidebar","description":"A composable, themeable and customizable sidebar component."},
	{"slug":"skeleton","name":"Skeleton","description":"Show a placeholder while content is loading."},
	{"slug":"slider","name":"Slider","description":"An input where the user selects a value from within a given range."},
	{"slug":"sonner","name":"Sonner","description":"An opinionated toast component."},
	{"slug":"switch-native","name":"Switch (Native)","description":"A native checkbox-based switch control."},
	{"slug":"table","name":"Table","description":"A responsive table component."},
	{"slug":"tabs","name":"Tabs","description":"Layered sections of content displayed one panel at a time."},
	{"slug":"textarea","name":"Textarea","description":"Displays a form textarea or a component that looks like a textarea."},
	{"slug":"theme-toggle","name":"Theme Toggle","description":"A button that toggles between light and dark mode."},
	{"slug":"time-field","name":"Time Field","description":"A segmented field that lets users enter and edit a time."},
	{"slug":"time-range-field","name":"Time Range Field","description":"A segmented field that lets users enter and edit a range of times."},
	{"slug":"toggle","name":"Toggle","description":"A two-state button that can be either on or off."},
	{"slug":"toggle-group","name":"Toggle Group","description":"A set of two-state buttons that can be toggled on or off."},
	{"slug":"toolbar","name":"Toolbar","description":"A container for grouping a set of controls such as buttons and toggles."},
	{"slug":"tooltip","name":"Tooltip","description":"A popup that displays information related to an element on hover or focus."},
] as const;

export const componentDemos = {
	"accordion": [
		{ key: "demo", name: "accordion-demo", path: "/src/lib/registry/accordion-demo.svelte", sourcePath: "../lib/registry/accordion-demo.svelte" },
	],
	"alert": [
		{ key: "demo", name: "alert-demo", path: "/src/lib/registry/alert-demo.svelte", sourcePath: "../lib/registry/alert-demo.svelte" },
	],
	"avatar": [
		{ key: "demo", name: "avatar-demo", path: "/src/lib/registry/avatar-demo.svelte", sourcePath: "../lib/registry/avatar-demo.svelte" },
		{ key: "group", name: "avatar-group", path: "/src/lib/registry/avatar-group.svelte", sourcePath: "../lib/registry/avatar-group.svelte" },
	],
	"badge": [
		{ key: "demo", name: "badge-demo", path: "/src/lib/registry/badge-demo.svelte", sourcePath: "../lib/registry/badge-demo.svelte" },
	],
	"breadcrumb": [
		{ key: "demo", name: "breadcrumb-demo", path: "/src/lib/registry/breadcrumb-demo.svelte", sourcePath: "../lib/registry/breadcrumb-demo.svelte" },
	],
	"button": [
		{ key: "demo", name: "button-demo", path: "/src/lib/registry/button-demo.svelte", sourcePath: "../lib/registry/button-demo.svelte" },
		{ key: "sizes", name: "button-sizes", path: "/src/lib/registry/button-sizes.svelte", sourcePath: "../lib/registry/button-sizes.svelte" },
		{ key: "with-icon", name: "button-with-icon", path: "/src/lib/registry/button-with-icon.svelte", sourcePath: "../lib/registry/button-with-icon.svelte" },
	],
	"calendar": [
		{ key: "demo", name: "calendar-demo", path: "/src/lib/registry/calendar-demo.svelte", sourcePath: "../lib/registry/calendar-demo.svelte" },
	],
	"card": [
		{ key: "demo", name: "card-demo", path: "/src/lib/registry/card-demo.svelte", sourcePath: "../lib/registry/card-demo.svelte" },
	],
	"carousel": [
		{ key: "demo", name: "carousel-demo", path: "/src/lib/registry/carousel-demo.svelte", sourcePath: "../lib/registry/carousel-demo.svelte" },
	],
	"carousel-native": [
		{ key: "demo", name: "carousel-native-demo", path: "/src/lib/registry/carousel-native-demo.svelte", sourcePath: "../lib/registry/carousel-native-demo.svelte" },
	],
	"chart": [
		{ key: "demo", name: "chart-demo", path: "/src/lib/registry/chart-demo.svelte", sourcePath: "../lib/registry/chart-demo.svelte" },
	],
	"checkbox": [
		{ key: "demo", name: "checkbox-demo", path: "/src/lib/registry/checkbox-demo.svelte", sourcePath: "../lib/registry/checkbox-demo.svelte" },
		{ key: "disabled", name: "checkbox-disabled", path: "/src/lib/registry/checkbox-disabled.svelte", sourcePath: "../lib/registry/checkbox-disabled.svelte" },
		{ key: "group", name: "checkbox-group", path: "/src/lib/registry/checkbox-group.svelte", sourcePath: "../lib/registry/checkbox-group.svelte" },
	],
	"checkbox-native": [
		{ key: "demo", name: "checkbox-native-demo", path: "/src/lib/registry/checkbox-native-demo.svelte", sourcePath: "../lib/registry/checkbox-native-demo.svelte" },
		{ key: "indeterminate", name: "checkbox-native-indeterminate", path: "/src/lib/registry/checkbox-native-indeterminate.svelte", sourcePath: "../lib/registry/checkbox-native-indeterminate.svelte" },
		{ key: "states", name: "checkbox-native-states", path: "/src/lib/registry/checkbox-native-states.svelte", sourcePath: "../lib/registry/checkbox-native-states.svelte" },
	],
	"collapsible": [
		{ key: "demo", name: "collapsible-demo", path: "/src/lib/registry/collapsible-demo.svelte", sourcePath: "../lib/registry/collapsible-demo.svelte" },
	],
	"combobox": [
		{ key: "demo", name: "combobox-demo", path: "/src/lib/registry/combobox-demo.svelte", sourcePath: "../lib/registry/combobox-demo.svelte" },
	],
	"command": [
		{ key: "demo", name: "command-demo", path: "/src/lib/registry/command-demo.svelte", sourcePath: "../lib/registry/command-demo.svelte" },
	],
	"context-menu": [
		{ key: "demo", name: "context-menu-demo", path: "/src/lib/registry/context-menu-demo.svelte", sourcePath: "../lib/registry/context-menu-demo.svelte" },
	],
	"data-table": [
		{ key: "demo", name: "data-table-demo", path: "/src/lib/registry/data-table-demo.svelte", sourcePath: "../lib/registry/data-table-demo.svelte" },
	],
	"date-field": [
		{ key: "demo", name: "date-field-demo", path: "/src/lib/registry/date-field-demo.svelte", sourcePath: "../lib/registry/date-field-demo.svelte" },
	],
	"date-picker": [
		{ key: "demo", name: "date-picker-demo", path: "/src/lib/registry/date-picker-demo.svelte", sourcePath: "../lib/registry/date-picker-demo.svelte" },
		{ key: "presets", name: "date-picker-presets", path: "/src/lib/registry/date-picker-presets.svelte", sourcePath: "../lib/registry/date-picker-presets.svelte" },
		{ key: "range", name: "date-picker-range", path: "/src/lib/registry/date-picker-range.svelte", sourcePath: "../lib/registry/date-picker-range.svelte" },
	],
	"date-range-field": [
		{ key: "demo", name: "date-range-field-demo", path: "/src/lib/registry/date-range-field-demo.svelte", sourcePath: "../lib/registry/date-range-field-demo.svelte" },
	],
	"dialog": [
		{ key: "demo", name: "dialog-demo", path: "/src/lib/registry/dialog-demo.svelte", sourcePath: "../lib/registry/dialog-demo.svelte" },
	],
	"drawer": [
		{ key: "demo", name: "drawer-demo", path: "/src/lib/registry/drawer-demo.svelte", sourcePath: "../lib/registry/drawer-demo.svelte" },
	],
	"dropdown-menu": [
		{ key: "demo", name: "dropdown-menu-demo", path: "/src/lib/registry/dropdown-menu-demo.svelte", sourcePath: "../lib/registry/dropdown-menu-demo.svelte" },
	],
	"empty": [
		{ key: "demo", name: "empty-demo", path: "/src/lib/registry/empty-demo.svelte", sourcePath: "../lib/registry/empty-demo.svelte" },
	],
	"field": [
		{ key: "demo", name: "field-demo", path: "/src/lib/registry/field-demo.svelte", sourcePath: "../lib/registry/field-demo.svelte" },
	],
	"heading": [
		{ key: "demo", name: "heading-demo", path: "/src/lib/registry/heading-demo.svelte", sourcePath: "../lib/registry/heading-demo.svelte" },
	],
	"input": [
		{ key: "demo", name: "input-demo", path: "/src/lib/registry/input-demo.svelte", sourcePath: "../lib/registry/input-demo.svelte" },
	],
	"item": [
		{ key: "demo", name: "item-demo", path: "/src/lib/registry/item-demo.svelte", sourcePath: "../lib/registry/item-demo.svelte" },
	],
	"kbd": [
		{ key: "demo", name: "kbd-demo", path: "/src/lib/registry/kbd-demo.svelte", sourcePath: "../lib/registry/kbd-demo.svelte" },
	],
	"label": [
		{ key: "demo", name: "label-demo", path: "/src/lib/registry/label-demo.svelte", sourcePath: "../lib/registry/label-demo.svelte" },
	],
	"link-preview": [
		{ key: "demo", name: "link-preview-demo", path: "/src/lib/registry/link-preview-demo.svelte", sourcePath: "../lib/registry/link-preview-demo.svelte" },
	],
	"menubar": [
		{ key: "demo", name: "menubar-demo", path: "/src/lib/registry/menubar-demo.svelte", sourcePath: "../lib/registry/menubar-demo.svelte" },
	],
	"meter": [
		{ key: "demo", name: "meter-demo", path: "/src/lib/registry/meter-demo.svelte", sourcePath: "../lib/registry/meter-demo.svelte" },
	],
	"native-dialog": [
		{ key: "demo", name: "native-dialog-demo", path: "/src/lib/registry/native-dialog-demo.svelte", sourcePath: "../lib/registry/native-dialog-demo.svelte" },
	],
	"native-select": [
		{ key: "demo", name: "native-select-demo", path: "/src/lib/registry/native-select-demo.svelte", sourcePath: "../lib/registry/native-select-demo.svelte" },
	],
	"navigation-menu": [
		{ key: "demo", name: "navigation-menu-demo", path: "/src/lib/registry/navigation-menu-demo.svelte", sourcePath: "../lib/registry/navigation-menu-demo.svelte" },
	],
	"pagination": [
		{ key: "demo", name: "pagination-demo", path: "/src/lib/registry/pagination-demo.svelte", sourcePath: "../lib/registry/pagination-demo.svelte" },
	],
	"pin-input": [
		{ key: "demo", name: "pin-input-demo", path: "/src/lib/registry/pin-input-demo.svelte", sourcePath: "../lib/registry/pin-input-demo.svelte" },
	],
	"popover": [
		{ key: "demo", name: "popover-demo", path: "/src/lib/registry/popover-demo.svelte", sourcePath: "../lib/registry/popover-demo.svelte" },
	],
	"progress": [
		{ key: "demo", name: "progress-demo", path: "/src/lib/registry/progress-demo.svelte", sourcePath: "../lib/registry/progress-demo.svelte" },
	],
	"radio-group": [
		{ key: "demo", name: "radio-group-demo", path: "/src/lib/registry/radio-group-demo.svelte", sourcePath: "../lib/registry/radio-group-demo.svelte" },
		{ key: "form", name: "radio-group-form", path: "/src/lib/registry/radio-group-form.svelte", sourcePath: "../lib/registry/radio-group-form.svelte" },
		{ key: "horizontal", name: "radio-group-horizontal", path: "/src/lib/registry/radio-group-horizontal.svelte", sourcePath: "../lib/registry/radio-group-horizontal.svelte" },
		{ key: "states", name: "radio-group-states", path: "/src/lib/registry/radio-group-states.svelte", sourcePath: "../lib/registry/radio-group-states.svelte" },
		{ key: "tiles", name: "radio-group-tiles", path: "/src/lib/registry/radio-group-tiles.svelte", sourcePath: "../lib/registry/radio-group-tiles.svelte" },
	],
	"range-calendar": [
		{ key: "demo", name: "range-calendar-demo", path: "/src/lib/registry/range-calendar-demo.svelte", sourcePath: "../lib/registry/range-calendar-demo.svelte" },
	],
	"resizable": [
		{ key: "demo", name: "resizable-demo", path: "/src/lib/registry/resizable-demo.svelte", sourcePath: "../lib/registry/resizable-demo.svelte" },
	],
	"scroll-area": [
		{ key: "demo", name: "scroll-area-demo", path: "/src/lib/registry/scroll-area-demo.svelte", sourcePath: "../lib/registry/scroll-area-demo.svelte" },
	],
	"select": [
		{ key: "demo", name: "select-demo", path: "/src/lib/registry/select-demo.svelte", sourcePath: "../lib/registry/select-demo.svelte" },
	],
	"separator": [
		{ key: "demo", name: "separator-demo", path: "/src/lib/registry/separator-demo.svelte", sourcePath: "../lib/registry/separator-demo.svelte" },
	],
	"sheet": [
		{ key: "demo", name: "sheet-demo", path: "/src/lib/registry/sheet-demo.svelte", sourcePath: "../lib/registry/sheet-demo.svelte" },
		{ key: "side", name: "sheet-side", path: "/src/lib/registry/sheet-side.svelte", sourcePath: "../lib/registry/sheet-side.svelte" },
	],
	"sidebar": [
		{ key: "demo", name: "sidebar-demo", path: "/src/lib/registry/sidebar-demo.svelte", sourcePath: "../lib/registry/sidebar-demo.svelte" },
		{ key: "floating", name: "sidebar-floating", path: "/src/lib/registry/sidebar-floating.svelte", sourcePath: "../lib/registry/sidebar-floating.svelte" },
		{ key: "right", name: "sidebar-right", path: "/src/lib/registry/sidebar-right.svelte", sourcePath: "../lib/registry/sidebar-right.svelte" },
	],
	"skeleton": [
		{ key: "demo", name: "skeleton-demo", path: "/src/lib/registry/skeleton-demo.svelte", sourcePath: "../lib/registry/skeleton-demo.svelte" },
	],
	"slider": [
		{ key: "demo", name: "slider-demo", path: "/src/lib/registry/slider-demo.svelte", sourcePath: "../lib/registry/slider-demo.svelte" },
		{ key: "range", name: "slider-range", path: "/src/lib/registry/slider-range.svelte", sourcePath: "../lib/registry/slider-range.svelte" },
	],
	"sonner": [
		{ key: "demo", name: "sonner-demo", path: "/src/lib/registry/sonner-demo.svelte", sourcePath: "../lib/registry/sonner-demo.svelte" },
	],
	"switch-native": [
		{ key: "demo", name: "switch-native-demo", path: "/src/lib/registry/switch-native-demo.svelte", sourcePath: "../lib/registry/switch-native-demo.svelte" },
		{ key: "states", name: "switch-native-states", path: "/src/lib/registry/switch-native-states.svelte", sourcePath: "../lib/registry/switch-native-states.svelte" },
	],
	"table": [
		{ key: "demo", name: "table-demo", path: "/src/lib/registry/table-demo.svelte", sourcePath: "../lib/registry/table-demo.svelte" },
	],
	"tabs": [
		{ key: "demo", name: "tabs-demo", path: "/src/lib/registry/tabs-demo.svelte", sourcePath: "../lib/registry/tabs-demo.svelte" },
	],
	"textarea": [
		{ key: "demo", name: "textarea-demo", path: "/src/lib/registry/textarea-demo.svelte", sourcePath: "../lib/registry/textarea-demo.svelte" },
	],
	"theme-toggle": [
		{ key: "demo", name: "theme-toggle-demo", path: "/src/lib/registry/theme-toggle-demo.svelte", sourcePath: "../lib/registry/theme-toggle-demo.svelte" },
	],
	"time-field": [
		{ key: "demo", name: "time-field-demo", path: "/src/lib/registry/time-field-demo.svelte", sourcePath: "../lib/registry/time-field-demo.svelte" },
	],
	"time-range-field": [
		{ key: "demo", name: "time-range-field-demo", path: "/src/lib/registry/time-range-field-demo.svelte", sourcePath: "../lib/registry/time-range-field-demo.svelte" },
	],
	"toggle": [
		{ key: "demo", name: "toggle-demo", path: "/src/lib/registry/toggle-demo.svelte", sourcePath: "../lib/registry/toggle-demo.svelte" },
		{ key: "disabled", name: "toggle-disabled", path: "/src/lib/registry/toggle-disabled.svelte", sourcePath: "../lib/registry/toggle-disabled.svelte" },
		{ key: "outline", name: "toggle-outline", path: "/src/lib/registry/toggle-outline.svelte", sourcePath: "../lib/registry/toggle-outline.svelte" },
	],
	"toggle-group": [
		{ key: "demo", name: "toggle-group-demo", path: "/src/lib/registry/toggle-group-demo.svelte", sourcePath: "../lib/registry/toggle-group-demo.svelte" },
		{ key: "multiple", name: "toggle-group-multiple", path: "/src/lib/registry/toggle-group-multiple.svelte", sourcePath: "../lib/registry/toggle-group-multiple.svelte" },
	],
	"toolbar": [
		{ key: "demo", name: "toolbar-demo", path: "/src/lib/registry/toolbar-demo.svelte", sourcePath: "../lib/registry/toolbar-demo.svelte" },
	],
	"tooltip": [
		{ key: "demo", name: "tooltip-demo", path: "/src/lib/registry/tooltip-demo.svelte", sourcePath: "../lib/registry/tooltip-demo.svelte" },
	],
} as const;

export const slugsWithDemos = new Set(
	Object.entries(componentDemos)
		.filter(([, demos]) => demos.length > 0)
		.map(([slug]) => slug)
);
