// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index = {
	"accordion-demo": {
		type: "registry:example",
		files: ["../lib/registry/accordion-demo.svelte"],
	},
	"alert-demo": {
		type: "registry:example",
		files: ["../lib/registry/alert-demo.svelte"],
	},
	"avatar-demo": {
		type: "registry:example",
		files: ["../lib/registry/avatar-demo.svelte"],
	},
	"avatar-group": {
		type: "registry:example",
		files: ["../lib/registry/avatar-group.svelte"],
	},
	"badge-demo": {
		type: "registry:example",
		files: ["../lib/registry/badge-demo.svelte"],
	},
	"breadcrumb-demo": {
		type: "registry:example",
		files: ["../lib/registry/breadcrumb-demo.svelte"],
	},
	"button-demo": {
		type: "registry:example",
		files: ["../lib/registry/button-demo.svelte"],
	},
	"button-sizes": {
		type: "registry:example",
		files: ["../lib/registry/button-sizes.svelte"],
	},
	"button-with-icon": {
		type: "registry:example",
		files: ["../lib/registry/button-with-icon.svelte"],
	},
	"calendar-demo": {
		type: "registry:example",
		files: ["../lib/registry/calendar-demo.svelte"],
	},
	"card-demo": {
		type: "registry:example",
		files: ["../lib/registry/card-demo.svelte"],
	},
	"carousel-demo": {
		type: "registry:example",
		files: ["../lib/registry/carousel-demo.svelte"],
	},
	"chart-demo": {
		type: "registry:example",
		files: ["../lib/registry/chart-demo.svelte"],
	},
	"checkbox-demo": {
		type: "registry:example",
		files: ["../lib/registry/checkbox-demo.svelte"],
	},
	"checkbox-disabled": {
		type: "registry:example",
		files: ["../lib/registry/checkbox-disabled.svelte"],
	},
	"checkbox-group": {
		type: "registry:example",
		files: ["../lib/registry/checkbox-group.svelte"],
	},
	"collapsible-demo": {
		type: "registry:example",
		files: ["../lib/registry/collapsible-demo.svelte"],
	},
	"combobox-demo": {
		type: "registry:example",
		files: ["../lib/registry/combobox-demo.svelte"],
	},
	"command-demo": {
		type: "registry:example",
		files: ["../lib/registry/command-demo.svelte"],
	},
	"context-menu-demo": {
		type: "registry:example",
		files: ["../lib/registry/context-menu-demo.svelte"],
	},
	"data-table-demo": {
		type: "registry:example",
		files: ["../lib/registry/data-table-demo.svelte"],
	},
	"date-field-demo": {
		type: "registry:example",
		files: ["../lib/registry/date-field-demo.svelte"],
	},
	"date-picker-demo": {
		type: "registry:example",
		files: ["../lib/registry/date-picker-demo.svelte"],
	},
	"date-picker-presets": {
		type: "registry:example",
		files: ["../lib/registry/date-picker-presets.svelte"],
	},
	"date-picker-range": {
		type: "registry:example",
		files: ["../lib/registry/date-picker-range.svelte"],
	},
	"date-range-field-demo": {
		type: "registry:example",
		files: ["../lib/registry/date-range-field-demo.svelte"],
	},
	"dialog-demo": {
		type: "registry:example",
		files: ["../lib/registry/dialog-demo.svelte"],
	},
	"drawer-demo": {
		type: "registry:example",
		files: ["../lib/registry/drawer-demo.svelte"],
	},
	"dropdown-menu-demo": {
		type: "registry:example",
		files: ["../lib/registry/dropdown-menu-demo.svelte"],
	},
	"empty-demo": {
		type: "registry:example",
		files: ["../lib/registry/empty-demo.svelte"],
	},
	"field-demo": {
		type: "registry:example",
		files: ["../lib/registry/field-demo.svelte"],
	},
	"heading-demo": {
		type: "registry:example",
		files: ["../lib/registry/heading-demo.svelte"],
	},
	"input-demo": {
		type: "registry:example",
		files: ["../lib/registry/input-demo.svelte"],
	},
	"item-demo": {
		type: "registry:example",
		files: ["../lib/registry/item-demo.svelte"],
	},
	"kbd-demo": {
		type: "registry:example",
		files: ["../lib/registry/kbd-demo.svelte"],
	},
	"label-demo": {
		type: "registry:example",
		files: ["../lib/registry/label-demo.svelte"],
	},
	"link-preview-demo": {
		type: "registry:example",
		files: ["../lib/registry/link-preview-demo.svelte"],
	},
	"menubar-demo": {
		type: "registry:example",
		files: ["../lib/registry/menubar-demo.svelte"],
	},
	"meter-demo": {
		type: "registry:example",
		files: ["../lib/registry/meter-demo.svelte"],
	},
	"native-dialog-demo": {
		type: "registry:example",
		files: ["../lib/registry/native-dialog-demo.svelte"],
	},
	"native-select-demo": {
		type: "registry:example",
		files: ["../lib/registry/native-select-demo.svelte"],
	},
	"navigation-menu-demo": {
		type: "registry:example",
		files: ["../lib/registry/navigation-menu-demo.svelte"],
	},
	"pagination-demo": {
		type: "registry:example",
		files: ["../lib/registry/pagination-demo.svelte"],
	},
	"pin-input-demo": {
		type: "registry:example",
		files: ["../lib/registry/pin-input-demo.svelte"],
	},
	"popover-demo": {
		type: "registry:example",
		files: ["../lib/registry/popover-demo.svelte"],
	},
	"progress-demo": {
		type: "registry:example",
		files: ["../lib/registry/progress-demo.svelte"],
	},
	"radio-group-demo": {
		type: "registry:example",
		files: ["../lib/registry/radio-group-demo.svelte"],
	},
	"range-calendar-demo": {
		type: "registry:example",
		files: ["../lib/registry/range-calendar-demo.svelte"],
	},
	"resizable-demo": {
		type: "registry:example",
		files: ["../lib/registry/resizable-demo.svelte"],
	},
	"scroll-area-demo": {
		type: "registry:example",
		files: ["../lib/registry/scroll-area-demo.svelte"],
	},
	"select-demo": {
		type: "registry:example",
		files: ["../lib/registry/select-demo.svelte"],
	},
	"separator-demo": {
		type: "registry:example",
		files: ["../lib/registry/separator-demo.svelte"],
	},
	"sheet-demo": {
		type: "registry:example",
		files: ["../lib/registry/sheet-demo.svelte"],
	},
	"sheet-side": {
		type: "registry:example",
		files: ["../lib/registry/sheet-side.svelte"],
	},
	"sidebar-demo": {
		type: "registry:example",
		files: ["../lib/registry/sidebar-demo.svelte"],
	},
	"sidebar-floating": {
		type: "registry:example",
		files: ["../lib/registry/sidebar-floating.svelte"],
	},
	"sidebar-right": {
		type: "registry:example",
		files: ["../lib/registry/sidebar-right.svelte"],
	},
	"skeleton-demo": {
		type: "registry:example",
		files: ["../lib/registry/skeleton-demo.svelte"],
	},
	"slider-demo": {
		type: "registry:example",
		files: ["../lib/registry/slider-demo.svelte"],
	},
	"slider-range": {
		type: "registry:example",
		files: ["../lib/registry/slider-range.svelte"],
	},
	"sonner-demo": {
		type: "registry:example",
		files: ["../lib/registry/sonner-demo.svelte"],
	},
	"switch-demo": {
		type: "registry:example",
		files: ["../lib/registry/switch-demo.svelte"],
	},
	"switch-native-demo": {
		type: "registry:example",
		files: ["../lib/registry/switch-native-demo.svelte"],
	},
	"table-demo": {
		type: "registry:example",
		files: ["../lib/registry/table-demo.svelte"],
	},
	"tabs-demo": {
		type: "registry:example",
		files: ["../lib/registry/tabs-demo.svelte"],
	},
	"textarea-demo": {
		type: "registry:example",
		files: ["../lib/registry/textarea-demo.svelte"],
	},
	"theme-toggle-demo": {
		type: "registry:example",
		files: ["../lib/registry/theme-toggle-demo.svelte"],
	},
	"time-field-demo": {
		type: "registry:example",
		files: ["../lib/registry/time-field-demo.svelte"],
	},
	"time-range-field-demo": {
		type: "registry:example",
		files: ["../lib/registry/time-range-field-demo.svelte"],
	},
	"toggle-demo": {
		type: "registry:example",
		files: ["../lib/registry/toggle-demo.svelte"],
	},
	"toggle-disabled": {
		type: "registry:example",
		files: ["../lib/registry/toggle-disabled.svelte"],
	},
	"toggle-group-demo": {
		type: "registry:example",
		files: ["../lib/registry/toggle-group-demo.svelte"],
	},
	"toggle-group-multiple": {
		type: "registry:example",
		files: ["../lib/registry/toggle-group-multiple.svelte"],
	},
	"toggle-outline": {
		type: "registry:example",
		files: ["../lib/registry/toggle-outline.svelte"],
	},
	"toolbar-demo": {
		type: "registry:example",
		files: ["../lib/registry/toolbar-demo.svelte"],
	},
	"tooltip-demo": {
		type: "registry:example",
		files: ["../lib/registry/tooltip-demo.svelte"],
	},
} as const;
