// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index = {
	"accordion-01-accordion": {
		type: "registry:example",
		files: ["../lib/registry/examples/accordion/01-accordion.svelte"],
	},
	"alert-01-alert": {
		type: "registry:example",
		files: ["../lib/registry/examples/alert/01-alert.svelte"],
	},
	"alert-dialog-01-alert-dialog": {
		type: "registry:example",
		files: ["../lib/registry/examples/alert-dialog/01-alert-dialog.svelte"],
	},
	"avatar-01-avatar": {
		type: "registry:example",
		files: ["../lib/registry/examples/avatar/01-avatar.svelte"],
	},
	"avatar-02-group": {
		type: "registry:example",
		files: ["../lib/registry/examples/avatar/02-group.svelte"],
	},
	"badge-01-variants": {
		type: "registry:example",
		files: ["../lib/registry/examples/badge/01-variants.svelte"],
	},
	"breadcrumb-01-breadcrumb": {
		type: "registry:example",
		files: ["../lib/registry/examples/breadcrumb/01-breadcrumb.svelte"],
	},
	"button-01-variants": {
		type: "registry:example",
		files: ["../lib/registry/examples/button/01-variants.svelte"],
	},
	"button-02-sizes": {
		type: "registry:example",
		files: ["../lib/registry/examples/button/02-sizes.svelte"],
	},
	"button-03-with-icon": {
		type: "registry:example",
		files: ["../lib/registry/examples/button/03-with-icon.svelte"],
	},
	"calendar-01-calendar": {
		type: "registry:example",
		files: ["../lib/registry/examples/calendar/01-calendar.svelte"],
	},
	"card-01-card": {
		type: "registry:example",
		files: ["../lib/registry/examples/card/01-card.svelte"],
	},
	"carousel-01-carousel": {
		type: "registry:example",
		files: ["../lib/registry/examples/carousel/01-carousel.svelte"],
	},
	"chart-01-chart": {
		type: "registry:example",
		files: ["../lib/registry/examples/chart/01-chart.svelte"],
	},
	"checkbox-01-checkbox": {
		type: "registry:example",
		files: ["../lib/registry/examples/checkbox/01-checkbox.svelte"],
	},
	"checkbox-02-group": {
		type: "registry:example",
		files: ["../lib/registry/examples/checkbox/02-group.svelte"],
	},
	"checkbox-03-disabled": {
		type: "registry:example",
		files: ["../lib/registry/examples/checkbox/03-disabled.svelte"],
	},
	"collapsible-01-collapsible": {
		type: "registry:example",
		files: ["../lib/registry/examples/collapsible/01-collapsible.svelte"],
	},
	"combobox-01-combobox": {
		type: "registry:example",
		files: ["../lib/registry/examples/combobox/01-combobox.svelte"],
	},
	"command-01-command": {
		type: "registry:example",
		files: ["../lib/registry/examples/command/01-command.svelte"],
	},
	"context-menu-01-context-menu": {
		type: "registry:example",
		files: ["../lib/registry/examples/context-menu/01-context-menu.svelte"],
	},
	"data-table-01-data-table": {
		type: "registry:example",
		files: ["../lib/registry/examples/data-table/01-data-table.svelte"],
	},
	"date-field-01-date-field": {
		type: "registry:example",
		files: ["../lib/registry/examples/date-field/01-date-field.svelte"],
	},
	"date-picker-01-date-picker": {
		type: "registry:example",
		files: ["../lib/registry/examples/date-picker/01-date-picker.svelte"],
	},
	"date-picker-02-presets": {
		type: "registry:example",
		files: ["../lib/registry/examples/date-picker/02-presets.svelte"],
	},
	"date-picker-03-range": {
		type: "registry:example",
		files: ["../lib/registry/examples/date-picker/03-range.svelte"],
	},
	"date-range-field-01-date-range-field": {
		type: "registry:example",
		files: ["../lib/registry/examples/date-range-field/01-date-range-field.svelte"],
	},
	"dialog-01-dialog": {
		type: "registry:example",
		files: ["../lib/registry/examples/dialog/01-dialog.svelte"],
	},
	"drawer-01-drawer": {
		type: "registry:example",
		files: ["../lib/registry/examples/drawer/01-drawer.svelte"],
	},
	"dropdown-menu-01-dropdown-menu": {
		type: "registry:example",
		files: ["../lib/registry/examples/dropdown-menu/01-dropdown-menu.svelte"],
	},
	"empty-01-empty": {
		type: "registry:example",
		files: ["../lib/registry/examples/empty/01-empty.svelte"],
	},
	"field-01-field": {
		type: "registry:example",
		files: ["../lib/registry/examples/field/01-field.svelte"],
	},
	"heading-01-heading": {
		type: "registry:example",
		files: ["../lib/registry/examples/heading/01-heading.svelte"],
	},
	"input-01-input": {
		type: "registry:example",
		files: ["../lib/registry/examples/input/01-input.svelte"],
	},
	"item-01-item": {
		type: "registry:example",
		files: ["../lib/registry/examples/item/01-item.svelte"],
	},
	"kbd-01-kbd": {
		type: "registry:example",
		files: ["../lib/registry/examples/kbd/01-kbd.svelte"],
	},
	"label-01-label": {
		type: "registry:example",
		files: ["../lib/registry/examples/label/01-label.svelte"],
	},
	"link-preview-01-link-preview": {
		type: "registry:example",
		files: ["../lib/registry/examples/link-preview/01-link-preview.svelte"],
	},
	"menubar-01-menubar": {
		type: "registry:example",
		files: ["../lib/registry/examples/menubar/01-menubar.svelte"],
	},
	"meter-01-meter": {
		type: "registry:example",
		files: ["../lib/registry/examples/meter/01-meter.svelte"],
	},
	"native-select-01-native-select": {
		type: "registry:example",
		files: ["../lib/registry/examples/native-select/01-native-select.svelte"],
	},
	"navigation-menu-01-navigation-menu": {
		type: "registry:example",
		files: ["../lib/registry/examples/navigation-menu/01-navigation-menu.svelte"],
	},
	"pagination-01-pagination": {
		type: "registry:example",
		files: ["../lib/registry/examples/pagination/01-pagination.svelte"],
	},
	"pin-input-01-pin-input": {
		type: "registry:example",
		files: ["../lib/registry/examples/pin-input/01-pin-input.svelte"],
	},
	"popover-01-popover": {
		type: "registry:example",
		files: ["../lib/registry/examples/popover/01-popover.svelte"],
	},
	"progress-01-progress": {
		type: "registry:example",
		files: ["../lib/registry/examples/progress/01-progress.svelte"],
	},
	"radio-group-01-radio-group": {
		type: "registry:example",
		files: ["../lib/registry/examples/radio-group/01-radio-group.svelte"],
	},
	"range-calendar-01-range-calendar": {
		type: "registry:example",
		files: ["../lib/registry/examples/range-calendar/01-range-calendar.svelte"],
	},
	"resizable-01-resizable": {
		type: "registry:example",
		files: ["../lib/registry/examples/resizable/01-resizable.svelte"],
	},
	"scroll-area-01-scroll-area": {
		type: "registry:example",
		files: ["../lib/registry/examples/scroll-area/01-scroll-area.svelte"],
	},
	"select-01-select": {
		type: "registry:example",
		files: ["../lib/registry/examples/select/01-select.svelte"],
	},
	"separator-01-separator": {
		type: "registry:example",
		files: ["../lib/registry/examples/separator/01-separator.svelte"],
	},
	"sheet-01-sheet": {
		type: "registry:example",
		files: ["../lib/registry/examples/sheet/01-sheet.svelte"],
	},
	"sheet-02-side": {
		type: "registry:example",
		files: ["../lib/registry/examples/sheet/02-side.svelte"],
	},
	"sidebar-01-sidebar": {
		type: "registry:example",
		files: ["../lib/registry/examples/sidebar/01-sidebar.svelte"],
	},
	"skeleton-01-skeleton": {
		type: "registry:example",
		files: ["../lib/registry/examples/skeleton/01-skeleton.svelte"],
	},
	"slider-01-slider": {
		type: "registry:example",
		files: ["../lib/registry/examples/slider/01-slider.svelte"],
	},
	"slider-02-range": {
		type: "registry:example",
		files: ["../lib/registry/examples/slider/02-range.svelte"],
	},
	"sonner-01-sonner": {
		type: "registry:example",
		files: ["../lib/registry/examples/sonner/01-sonner.svelte"],
	},
	"spinner-01-spinner": {
		type: "registry:example",
		files: ["../lib/registry/examples/spinner/01-spinner.svelte"],
	},
	"switch-01-switch": {
		type: "registry:example",
		files: ["../lib/registry/examples/switch/01-switch.svelte"],
	},
	"switch-native-01-switch-native": {
		type: "registry:example",
		files: ["../lib/registry/examples/switch-native/01-switch-native.svelte"],
	},
	"table-01-table": {
		type: "registry:example",
		files: ["../lib/registry/examples/table/01-table.svelte"],
	},
	"tabs-01-tabs": {
		type: "registry:example",
		files: ["../lib/registry/examples/tabs/01-tabs.svelte"],
	},
	"textarea-01-textarea": {
		type: "registry:example",
		files: ["../lib/registry/examples/textarea/01-textarea.svelte"],
	},
	"theme-toggle-01-theme-toggle": {
		type: "registry:example",
		files: ["../lib/registry/examples/theme-toggle/01-theme-toggle.svelte"],
	},
	"time-field-01-time-field": {
		type: "registry:example",
		files: ["../lib/registry/examples/time-field/01-time-field.svelte"],
	},
	"time-range-field-01-time-range-field": {
		type: "registry:example",
		files: ["../lib/registry/examples/time-range-field/01-time-range-field.svelte"],
	},
	"toggle-01-toggle": {
		type: "registry:example",
		files: ["../lib/registry/examples/toggle/01-toggle.svelte"],
	},
	"toggle-02-outline": {
		type: "registry:example",
		files: ["../lib/registry/examples/toggle/02-outline.svelte"],
	},
	"toggle-03-disabled": {
		type: "registry:example",
		files: ["../lib/registry/examples/toggle/03-disabled.svelte"],
	},
	"toggle-group-01-toggle-group": {
		type: "registry:example",
		files: ["../lib/registry/examples/toggle-group/01-toggle-group.svelte"],
	},
	"toggle-group-02-multiple": {
		type: "registry:example",
		files: ["../lib/registry/examples/toggle-group/02-multiple.svelte"],
	},
	"toolbar-01-toolbar": {
		type: "registry:example",
		files: ["../lib/registry/examples/toolbar/01-toolbar.svelte"],
	},
	"tooltip-01-tooltip": {
		type: "registry:example",
		files: ["../lib/registry/examples/tooltip/01-tooltip.svelte"],
	},
} as const;
