import fs from "node:fs";
import path from "node:path";
import { components } from "../src/routes/components/_registry.js";

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, "src");
const GENERATED_DIR = path.join(SRC_DIR, "__registry__");
const REGISTRY_DIR = path.join(SRC_DIR, "lib", "registry");
const BLOCKS_DIR = path.join(SRC_DIR, "lib", "blocks");

type DemoEntry = {
	key: string;
	name: string;
	path: string;
	sourcePath: string;
};

function writeFileWithDirs(filePath: string, data: string) {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, data, "utf8");
}

function toPosix(filePath: string) {
	return filePath.split(path.sep).join("/");
}

function quote(value: string) {
	return JSON.stringify(value);
}

function readDemoEntries() {
	const demosBySlug = new Map<string, DemoEntry[]>();

	if (!fs.existsSync(REGISTRY_DIR)) return demosBySlug;

	// Demos live flat in registry/ named `<slug>-<descriptor>.svelte` (shadcn
	// convention; the default example is `<slug>-demo.svelte`). The owning slug
	// is the longest known component slug that prefixes the filename — sort
	// longest-first so multi-word slugs (alert-dialog, toggle-group) win over
	// their shorter prefixes (alert, toggle).
	const slugs = components.map((component) => component.slug).sort((a, b) => b.length - a.length);

	for (const entry of fs.readdirSync(REGISTRY_DIR, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith(".svelte")) continue;

		const name = entry.name.slice(0, -".svelte".length);
		const slug = slugs.find((s) => name === s || name.startsWith(`${s}-`));
		if (!slug) {
			throw new Error(`Demo file has no matching component slug: ${entry.name}`);
		}

		const key = name === slug ? "demo" : name.slice(slug.length + 1);
		const demos = demosBySlug.get(slug) ?? [];
		demos.push({
			key,
			name,
			path: `/src/lib/registry/${entry.name}`,
			sourcePath: `../lib/registry/${entry.name}`,
		});
		demosBySlug.set(slug, demos);
	}

	for (const demos of demosBySlug.values()) {
		demos.sort((a, b) => a.key.localeCompare(b.key));
	}

	return demosBySlug;
}

function readBlocks() {
	if (!fs.existsSync(BLOCKS_DIR)) return [];

	return fs
		.readdirSync(BLOCKS_DIR, { withFileTypes: true })
		.flatMap((entry) => {
			if (entry.isDirectory()) return [entry.name];
			if (entry.isFile() && entry.name.endsWith(".svelte")) {
				return [entry.name.slice(0, -".svelte".length)];
			}
			return [];
		})
		.sort((a, b) => a.localeCompare(b));
}

function buildComponentsFile(demosBySlug: Map<string, DemoEntry[]>) {
	const componentLines = components
		.map(
			(component) =>
				`\t${JSON.stringify({
					slug: component.slug,
					name: component.name,
					description: component.description,
				})},`
		)
		.join("\n");

	const demoLines = components
		.map((component) => {
			const demos = demosBySlug.get(component.slug) ?? [];
			const entries = demos
				.map(
					(demo) =>
						`\t\t{ key: ${quote(demo.key)}, name: ${quote(demo.name)}, path: ${quote(demo.path)}, sourcePath: ${quote(demo.sourcePath)} },`
				)
				.join("\n");
			return `\t${quote(component.slug)}: [\n${entries}\n\t],`;
		})
		.join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const components = [
${componentLines}
] as const;

export const componentDemos = {
${demoLines}
} as const;

export const slugsWithDemos = new Set(
\tObject.entries(componentDemos)
\t\t.filter(([, demos]) => demos.length > 0)
\t\t.map(([slug]) => slug)
);
`;
}

function buildIndexFile(demosBySlug: Map<string, DemoEntry[]>) {
	const entries = [...demosBySlug.values()]
		.flat()
		.sort((a, b) => a.name.localeCompare(b.name))
		.map((demo) => {
			return `\t${quote(demo.name)}: {
\t\ttype: "registry:example",
\t\tfiles: [${quote(demo.sourcePath)}],
\t},`;
		})
		.join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index = {
${entries}
} as const;
`;
}

function buildBlocksFile(blocks: string[]) {
	const blockLines = blocks.map((block) => `\t${quote(block)},`).join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const blocks = [
${blockLines}
] as const;
`;
}

function validateDemoCoverage(demosBySlug: Map<string, DemoEntry[]>) {
	const knownSlugs = new Set(components.map((component) => component.slug));
	const unknownSlugs = [...demosBySlug.keys()].filter((slug) => !knownSlugs.has(slug));
	if (unknownSlugs.length) {
		throw new Error(`Demo folders without component metadata: ${unknownSlugs.join(", ")}`);
	}
}

export function buildRegistry() {
	const demosBySlug = readDemoEntries();
	validateDemoCoverage(demosBySlug);

	const blocks = readBlocks();

	writeFileWithDirs(path.join(GENERATED_DIR, "components.ts"), buildComponentsFile(demosBySlug));
	writeFileWithDirs(path.join(GENERATED_DIR, "index.ts"), buildIndexFile(demosBySlug));
	writeFileWithDirs(path.join(GENERATED_DIR, "blocks.ts"), buildBlocksFile(blocks));

	console.log(
		`[registry]: generated ${components.length} components, ${[...demosBySlug.values()].flat().length} demos, ${blocks.length} blocks`
	);
}

if (toPosix(process.argv[1] ?? "").endsWith("scripts/build-registry.ts")) {
	buildRegistry();
}
