import fs from "node:fs";
import path from "node:path";
import { components } from "../src/routes/components/_registry.js";

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, "src");
const GENERATED_DIR = path.join(SRC_DIR, "__registry__");
const EXAMPLES_DIR = path.join(SRC_DIR, "lib", "registry", "examples");
const BLOCKS_DIR = path.join(SRC_DIR, "lib", "blocks");

type DemoEntry = {
	key: string;
	name: string;
	path: string;
	sourcePath: string;
};

function writeFileWithDirs(filePath: string, data: string) {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, data, "utf8");
}

function toPosix(filePath: string) {
	return filePath.split(path.sep).join("/");
}

function quote(value: string) {
	return JSON.stringify(value);
}

function readDemoEntries() {
	const demosBySlug = new Map<string, DemoEntry[]>();

	if (!fs.existsSync(EXAMPLES_DIR)) return demosBySlug;

	for (const slugDir of fs.readdirSync(EXAMPLES_DIR, { withFileTypes: true })) {
		if (!slugDir.isDirectory()) continue;

		const slug = slugDir.name;
		const dir = path.join(EXAMPLES_DIR, slug);
		const demos = fs
			.readdirSync(dir, { withFileTypes: true })
			.filter((entry) => entry.isFile() && entry.name.endsWith(".svelte"))
			.map((entry) => {
				const key = entry.name.slice(0, -".svelte".length);
				return {
					key,
					name: `${slug}-${key}`,
					path: `/src/lib/registry/examples/${slug}/${entry.name}`,
					sourcePath: `../lib/registry/examples/${slug}/${entry.name}`,
				};
			})
			.sort((a, b) => a.key.localeCompare(b.key));

		if (demos.length) demosBySlug.set(slug, demos);
	}

	return demosBySlug;
}

function readBlocks() {
	if (!fs.existsSync(BLOCKS_DIR)) return [];

	return fs
		.readdirSync(BLOCKS_DIR, { withFileTypes: true })
		.flatMap((entry) => {
			if (entry.isDirectory()) return [entry.name];
			if (entry.isFile() && entry.name.endsWith(".svelte")) {
				return [entry.name.slice(0, -".svelte".length)];
			}
			return [];
		})
		.sort((a, b) => a.localeCompare(b));
}

function buildComponentsFile(demosBySlug: Map<string, DemoEntry[]>) {
	const componentLines = components
		.map(
			(component) =>
				`\t${JSON.stringify({
					slug: component.slug,
					name: component.name,
					description: component.description,
				})},`
		)
		.join("\n");

	const demoLines = components
		.map((component) => {
			const demos = demosBySlug.get(component.slug) ?? [];
			const entries = demos
				.map(
					(demo) =>
						`\t\t{ key: ${quote(demo.key)}, name: ${quote(demo.name)}, path: ${quote(demo.path)}, sourcePath: ${quote(demo.sourcePath)} },`
				)
				.join("\n");
			return `\t${quote(component.slug)}: [\n${entries}\n\t],`;
		})
		.join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const components = [
${componentLines}
] as const;

export const componentDemos = {
${demoLines}
} as const;

export const slugsWithDemos = new Set(
\tObject.entries(componentDemos)
\t\t.filter(([, demos]) => demos.length > 0)
\t\t.map(([slug]) => slug)
);
`;
}

function buildIndexFile(demosBySlug: Map<string, DemoEntry[]>) {
	const entries = [...demosBySlug.values()]
		.flat()
		.sort((a, b) => a.name.localeCompare(b.name))
		.map((demo) => {
			return `\t${quote(demo.name)}: {
\t\ttype: "registry:example",
\t\tfiles: [${quote(demo.sourcePath)}],
\t},`;
		})
		.join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const Index = {
${entries}
} as const;
`;
}

function buildBlocksFile(blocks: string[]) {
	const blockLines = blocks.map((block) => `\t${quote(block)},`).join("\n");

	return `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

export const blocks = [
${blockLines}
] as const;
`;
}

function validateDemoCoverage(demosBySlug: Map<string, DemoEntry[]>) {
	const knownSlugs = new Set(components.map((component) => component.slug));
	const unknownSlugs = [...demosBySlug.keys()].filter((slug) => !knownSlugs.has(slug));
	if (unknownSlugs.length) {
		throw new Error(`Demo folders without component metadata: ${unknownSlugs.join(", ")}`);
	}
}

export function buildRegistry() {
	const demosBySlug = readDemoEntries();
	validateDemoCoverage(demosBySlug);

	const blocks = readBlocks();

	writeFileWithDirs(path.join(GENERATED_DIR, "components.ts"), buildComponentsFile(demosBySlug));
	writeFileWithDirs(path.join(GENERATED_DIR, "index.ts"), buildIndexFile(demosBySlug));
	writeFileWithDirs(path.join(GENERATED_DIR, "blocks.ts"), buildBlocksFile(blocks));

	console.log(
		`[registry]: generated ${components.length} components, ${[...demosBySlug.values()].flat().length} demos, ${blocks.length} blocks`
	);
}

if (toPosix(process.argv[1] ?? "").endsWith("scripts/build-registry.ts")) {
	buildRegistry();
}
